### PR TITLE
Telegraf kepler integration

### PR DESCRIPTION
**Pull request by Shobhij**

### CODE REVIEW

**Comment by Shobhij** [comment]
@rootfs I have fixed the lint error and rebased my changes in this new pull request.

**Review by maryamtahhan — APPROVED** [review]
LGTM

Thanks @Shobhij for the updates

**Comment by Shobhij** [comment]
> LGTM
> 
> Thanks @Shobhij for the updates

Thanks Maryam for all the help in solving linter checks initially!!

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
Thanks!

**Pull request merged**
