### PR TITLE
Updates to kepler-doc repo

### PR DESCRIPTION
**Pull request by ramachandranravi**
Following updates were made:
1. docs/developer folder has been created and added design and Grafana dashboard snapshots
$ tree docs/
docs/
├── developer
│   ├── architecture.md
│   └── assets
│       ├── design-architecture.png
│       └── grafana-dashboard.png
2. docs/user-guide has been created and added grafana-deploy flow design.
$ tree docs/user-guides/
docs/user-guides/
└── assets
    └── grafana-deploy.png

### CODE REVIEW

**Comment by rootfs** [comment]
@ramachandranravi can you sign the commit?

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~2 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin add-UserGuide-archdiagrams

**Comment by ramachandranravi** [comment]
> @ramachandranravi can you sign the commit?
> 
> To add your Signed-off-by line to every commit in this branch:
> 
> Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally). In your local branch, run: git rebase HEAD~2 --signoff Force push your changes to overwrite the branch: git push --force-with-lease origin add-UserGuide-archdiagrams

Hi @rootfs It is done now. Thanks!

**Comment by sthaha** [comment]
@ramachandranravi , Thank you for the PR. I think the operator architecture.md should go into kepler-operator repo instead of the doc so that design changes can be kept in sync.

**Comment by sthaha** [comment]
All `developer` docs should reside under its corresponding project and IMHO, this repo should be used for user-guides.

**Pull request closed without merging**
