### PR TITLE
enhance doc: add metrics

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
@marceloamaral can you take a quick look?

**Review by marceloamaral — APPROVED** [review]
/lgtm

**Comment by marceloamaral** [comment]
I don't have the rights to do merge in this repo

**Review by marceloamaral — APPROVED** [review]

**Comment by husky-parul** [comment]
We are deciding b/w mkdocs vs hugo vs sphinx. That's why all PRs are on hold until we finalize that.

**Comment by rootfs** [comment]
@marceloamaral you should have the merge right now, can you test it?

**Comment by husky-parul** [comment]
We have migrated to mkdocs. This PR needs a rebase.
**cc:** @jichenjc @marceloamaral

**Pull request merged**
