### PR TITLE
Update local-cluster.md

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
The current code snippet is missing things to make it workable.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
I also don't think the `make cluster-up` command mentioned will do anything, but maybe I missed something

**Comment by ChrisChinchilla** [comment]
Yeah sorry I think it's because I did it through the GitHub ui. Will need to clone the repo etc to do it. Will do it asap

**Comment by ChrisChinchilla** [comment]
@SamYuan1990 Done

**Review by SamYuan1990 — APPROVED** [review]
LGTM

**Pull request merged**
